Try to configure sensors only once

diff --git a/src/scripts/install.sh.in b/src/scripts/install.sh.in
--- a/src/scripts/install.sh.in
+++ b/src/scripts/install.sh.in
@@ -171,9 +171,10 @@ EOF
     if (( CONFIGURE_SENSORS )); then
         state "Configure sensors"
         target-install lm_sensors
-        while ! target-exec sensors-detect; do
+        if ! target-exec sensors-detect; then
+            echo "Errors occurred. Skip configuring sensors..."
             sleep 1
-        done
+        fi
     fi
 
     if (( CONFIGURE_FIREWALL )); then
